# This is a basic fully hermetic run of Lighthouse, that saves results as run artifacts.
name: LHCI-upload-artifact
on: push
jobs:
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Lighthouse on urls!
        uses: treosh/lighthouse-ci-action@netlify
        with:
          urls: |
            https://magical-cedar-7feef.netlify.com
            https://magical-cedar-7feef.netlify.com/about/
            https://magical-cedar-7feef.netlify.com/style-guide/
          logLevel: 'info'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          applicationGithubToken: ${{ secrets.GITHUB_TOKEN }}
          personalGithubToken: ${{ secrets.GITHUB_TOKEN_PERMISSIONS }}
          netlifySite: 'magical-cedar-7feef.netlify.com'
          budgetPath: '.github/budget.json'
          notifications: |
            slack
