# This is a basic fully hermetic run of Lighthouse, that saves results as run artifacts.
name: LHCI-upload-artifact
on: push
jobs:
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "magical-cedar-7feef"
          max_timeout: 6000
      - name: Run Lighthouse on urls!
        uses: treosh/lighthouse-ci-action@next
        with:
          urls: |
            https://magical-cedar-7feef.netlify.com
            https://magical-cedar-7feef.netlify.com/about
            https://magical-cedar-7feef.netlify.com/style-guide/
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          applicationGithubToken: ${{ secrets.GITHUB_TOKEN }}
          personalGithubToken: ${{ secrets.GITHUB_TOKEN_PERMISSIONS }}
          budgetPath: '.github/budget.json'
          notifications: |
            slack
